/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExternalApiRouteImport } from './routes/external-api'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KsasIndexRouteImport } from './routes/ksas.index'
import { Route as KsasWorkProgressRouteImport } from './routes/ksas.work-progress'
import { Route as KsasSearchRouteImport } from './routes/ksas.search'
import { Route as KsasPlantingPlanRouteImport } from './routes/ksas.planting-plan'
import { Route as KsasLogsRouteImport } from './routes/ksas.logs'
import { Route as KsasInstructionRouteImport } from './routes/ksas.instruction'
import { Route as KsasFieldLedgerRouteImport } from './routes/ksas.field-ledger'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalApiRoute = ExternalApiRouteImport.update({
  id: '/external-api',
  path: '/external-api',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasIndexRoute = KsasIndexRouteImport.update({
  id: '/ksas/',
  path: '/ksas/',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasWorkProgressRoute = KsasWorkProgressRouteImport.update({
  id: '/ksas/work-progress',
  path: '/ksas/work-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasSearchRoute = KsasSearchRouteImport.update({
  id: '/ksas/search',
  path: '/ksas/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasPlantingPlanRoute = KsasPlantingPlanRouteImport.update({
  id: '/ksas/planting-plan',
  path: '/ksas/planting-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasLogsRoute = KsasLogsRouteImport.update({
  id: '/ksas/logs',
  path: '/ksas/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasInstructionRoute = KsasInstructionRouteImport.update({
  id: '/ksas/instruction',
  path: '/ksas/instruction',
  getParentRoute: () => rootRouteImport,
} as any)
const KsasFieldLedgerRoute = KsasFieldLedgerRouteImport.update({
  id: '/ksas/field-ledger',
  path: '/ksas/field-ledger',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/external-api': typeof ExternalApiRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/ksas/field-ledger': typeof KsasFieldLedgerRoute
  '/ksas/instruction': typeof KsasInstructionRoute
  '/ksas/logs': typeof KsasLogsRoute
  '/ksas/planting-plan': typeof KsasPlantingPlanRoute
  '/ksas/search': typeof KsasSearchRoute
  '/ksas/work-progress': typeof KsasWorkProgressRoute
  '/ksas/': typeof KsasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/external-api': typeof ExternalApiRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/ksas/field-ledger': typeof KsasFieldLedgerRoute
  '/ksas/instruction': typeof KsasInstructionRoute
  '/ksas/logs': typeof KsasLogsRoute
  '/ksas/planting-plan': typeof KsasPlantingPlanRoute
  '/ksas/search': typeof KsasSearchRoute
  '/ksas/work-progress': typeof KsasWorkProgressRoute
  '/ksas': typeof KsasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/external-api': typeof ExternalApiRoute
  '/library': typeof LibraryRoute
  '/map': typeof MapRoute
  '/ksas/field-ledger': typeof KsasFieldLedgerRoute
  '/ksas/instruction': typeof KsasInstructionRoute
  '/ksas/logs': typeof KsasLogsRoute
  '/ksas/planting-plan': typeof KsasPlantingPlanRoute
  '/ksas/search': typeof KsasSearchRoute
  '/ksas/work-progress': typeof KsasWorkProgressRoute
  '/ksas/': typeof KsasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge'
    | '/external-api'
    | '/library'
    | '/map'
    | '/ksas/field-ledger'
    | '/ksas/instruction'
    | '/ksas/logs'
    | '/ksas/planting-plan'
    | '/ksas/search'
    | '/ksas/work-progress'
    | '/ksas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridge'
    | '/external-api'
    | '/library'
    | '/map'
    | '/ksas/field-ledger'
    | '/ksas/instruction'
    | '/ksas/logs'
    | '/ksas/planting-plan'
    | '/ksas/search'
    | '/ksas/work-progress'
    | '/ksas'
  id:
    | '__root__'
    | '/'
    | '/bridge'
    | '/external-api'
    | '/library'
    | '/map'
    | '/ksas/field-ledger'
    | '/ksas/instruction'
    | '/ksas/logs'
    | '/ksas/planting-plan'
    | '/ksas/search'
    | '/ksas/work-progress'
    | '/ksas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeRoute: typeof BridgeRoute
  ExternalApiRoute: typeof ExternalApiRoute
  LibraryRoute: typeof LibraryRoute
  MapRoute: typeof MapRoute
  KsasFieldLedgerRoute: typeof KsasFieldLedgerRoute
  KsasInstructionRoute: typeof KsasInstructionRoute
  KsasLogsRoute: typeof KsasLogsRoute
  KsasPlantingPlanRoute: typeof KsasPlantingPlanRoute
  KsasSearchRoute: typeof KsasSearchRoute
  KsasWorkProgressRoute: typeof KsasWorkProgressRoute
  KsasIndexRoute: typeof KsasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-api': {
      id: '/external-api'
      path: '/external-api'
      fullPath: '/external-api'
      preLoaderRoute: typeof ExternalApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/': {
      id: '/ksas/'
      path: '/ksas'
      fullPath: '/ksas/'
      preLoaderRoute: typeof KsasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/work-progress': {
      id: '/ksas/work-progress'
      path: '/ksas/work-progress'
      fullPath: '/ksas/work-progress'
      preLoaderRoute: typeof KsasWorkProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/search': {
      id: '/ksas/search'
      path: '/ksas/search'
      fullPath: '/ksas/search'
      preLoaderRoute: typeof KsasSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/planting-plan': {
      id: '/ksas/planting-plan'
      path: '/ksas/planting-plan'
      fullPath: '/ksas/planting-plan'
      preLoaderRoute: typeof KsasPlantingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/logs': {
      id: '/ksas/logs'
      path: '/ksas/logs'
      fullPath: '/ksas/logs'
      preLoaderRoute: typeof KsasLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/instruction': {
      id: '/ksas/instruction'
      path: '/ksas/instruction'
      fullPath: '/ksas/instruction'
      preLoaderRoute: typeof KsasInstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksas/field-ledger': {
      id: '/ksas/field-ledger'
      path: '/ksas/field-ledger'
      fullPath: '/ksas/field-ledger'
      preLoaderRoute: typeof KsasFieldLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeRoute: BridgeRoute,
  ExternalApiRoute: ExternalApiRoute,
  LibraryRoute: LibraryRoute,
  MapRoute: MapRoute,
  KsasFieldLedgerRoute: KsasFieldLedgerRoute,
  KsasInstructionRoute: KsasInstructionRoute,
  KsasLogsRoute: KsasLogsRoute,
  KsasPlantingPlanRoute: KsasPlantingPlanRoute,
  KsasSearchRoute: KsasSearchRoute,
  KsasWorkProgressRoute: KsasWorkProgressRoute,
  KsasIndexRoute: KsasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
